In [10]:
a=2
a

2

In [6]:
1w=12

SyntaxError: invalid syntax (<ipython-input-6-6f2d01d88f77>, line 1)

In [12]:
A=1+2+3+\
4+5+6+\
7+8+9

A

45

In [14]:
A=(1+2+3+
  4+5+6+
  7+8+9)
A

45

In [15]:
a,b,c=1

TypeError: cannot unpack non-iterable int object

In [18]:
a,b,c=1,2,4
print(a) 

1


a=b=c=1
a

In [20]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
for i in range(10):
    print(i)
    if(i==5):
        break
    

0
1
2
3
4
5


In [29]:
a=10
if a<20:
    print(a)
    

10


In [31]:
#hello statement
print ("hello");

hello


In [33]:
"""Function to 
double
the value"""

'Function to \ndouble\nthe value'

In [34]:
def doc_str(num):
    """function to return the sum"""
    return 100-num

In [37]:
doc_str(1000)

-900

In [41]:
print (doc_str.__doc__)

function to return the sum


In [42]:
import os

pwd=os.getcwd()
print(pwd)

C:\Users\SakthivelSundaram\Desktop\personal\Learning


In [43]:
import cons

print(cons.PI)

3.14


In [49]:
ls=[1,1,2.40,"threee"]
print(ls)
type(ls)

[1, 1, 2.4, 'threee']


list

In [50]:
list3 =[1,2,3,4,5,6]
print (list3)

[1, 2, 3, 4, 5, 6]


In [53]:
list3[2:6]

[3, 4, 5, 6]

In [55]:
list3[5]="last element"
list3

[1, 2, 3, 4, 5, 'last element']

In [56]:
tup=(1,2,3)
print (tup)

(1, 2, 3)


In [57]:
type (tup)

tuple

In [61]:
tup[2]="o"

TypeError: 'tuple' object does not support item assignment

In [62]:
s1={1,2,3,4,5,6}
type(s1)

set

In [63]:
s1[3]=22
print(s1)

TypeError: 'set' object does not support item assignment

In [64]:
print(s1)

{1, 2, 3, 4, 5, 6}


In [65]:
print(s1)

{1, 2, 3, 4, 5, 6}


In [70]:
dict2={"p":'AAA',2:"BBB"}
print(dict2)

{'p': 'AAA', 2: 'BBB'}


In [74]:
float(10)

10.0

In [72]:
int(10.7)

10

In [75]:
int("IP")

ValueError: invalid literal for int() with base 10: 'IP'

In [76]:
int("456")

456

In [79]:
a22=int("456")
print(a22)

456


In [80]:
list4=[45,67,89,23,54]
type(list4)

list

In [86]:
sf=set(list4)
print(sf)
print(sf)


{67, 45, 54, 23, 89}
{67, 45, 54, 23, 89}


In [85]:
print(list4)

[45, 67, 89, 23, 54]


In [87]:
tuple(sf)

(67, 45, 54, 23, 89)

In [91]:
num_int=123
num_flo=12.4
num_add=num_int+num_flo
print("value of num_add",num_add)

value of num_add 135.4


In [90]:
print ("type of num_add",type(num_add))

type of num_add <class 'float'>


In [96]:
num_int=123
num_flo=12.4
num_str="456"
num_add=num_int+num_flo+num_str
print("value of num_add",num_add)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [102]:

num_int=123
num_flo=12.4
num_str="456"
num_str=int(num_str)
num_add=num_int+num_flo+int(num_str)
print("value of num_add",num_add)


value of num_add 591.4


In [113]:
#comparsion operators
3!=3
3>2
3<2
3>=2
3<=2


False

In [117]:
#logical operators

3>2 or 3<2
not (3>2 and 3<2)


True

In [123]:
num = int(input ("Enter the number: "))

if num>0:
    print (num)
else:
    if num==0:
        print(0)
    else:
        print (-(num))
    


Enter the number: -9
9


In [125]:
for i in range(10):
    j=i//2
    if(j==0):
        print(i," is even")
    else:
        print(i," is Odd")

0  is even
1  is even
2  is Odd
3  is Odd
4  is Odd
5  is Odd
6  is Odd
7  is Odd
8  is Odd
9  is Odd


In [127]:
num= int(input("Entere the number:"))
i=0
sum=0
while(i<num):
    if(i in range(0,5)):
        sum=sum+i
    else:
        sum=sum+10
    i=i+1
print(sum)

Entere the number:20
160


In [132]:
for i in "Higher":
    if i =="i":
        continue
    if i=="h":
        break
    
    else:
        print(i)
        

H
g


In [135]:
def my_fun(num):
    if num>=0:
        print (num)
    else:
        print (-num)

my_fun(0)

0


# Default Parameter
### if argument is not passed , then take default argument
### if passed , then override
### Default arguments should be at the last , else all the arguments should have default value, but should not be at the first

In [143]:
def my_fun(arg1,arg3="EveryOne"):
    print(arg1," " ,arg3)
my_fun("Good Morning")
my_fun("Good Morning","Sakthi")

Good Morning   EveryOne
Good Morning   Sakthi


# orbitary Arguments 

## takes any number of arguments

In [146]:
def my_def(*names):
    for i in names:
        print (i)

my_def("Sakthi","Mano","Thisanth")

Sakthi
Mano
Thisanth


## Recursion 

### Calling the function again and again

In [148]:
def rec(x):
    if x==1:
        return x
    else:
        return (x*rec(x-1))

print("factorial is ",rec(5))


factorial is  120


## lambda function

In [190]:
cube=lambda x:x**3
print(cube(4))





64


# filter Function

## 'filter(function or None, iterable) --> filter object\n\nReturn an iterator yielding those items of iterable for which function(item)\nis true. If function is None, return the items that are true.'

In [162]:
mylist = range(0,10)
print (mylist)
ls = list(filter(lambda x: x%2!=0,mylist))
print(ls)

filter.__doc__

range(0, 10)
[1, 3, 5, 7, 9]


'filter(function or None, iterable) --> filter object\n\nReturn an iterator yielding those items of iterable for which function(item)\nis true. If function is None, return the items that are true.'

# Map Function 
## map(func, *iterables) --> map object\n\nMake an iterator that computes the function using arguments from\neach of the iterables.  Stops when the shortest iterable is exhausted.'

mylist = range(0,10)
print (mylist)
ls = list(map(lambda x: x%2!=0,mylist))
print(ls)
ls1=list(map(lambda x:x*x,mylist))
print(ls1)
map.__doc__

# Global Variable 

## we can access the global variable inside a function . 
## But , in order to assign , we need to tell function its a global variable

In [38]:
var =20 
def fun():
    
    #print ("before assignment",var)
    global var
    var = var+2
    print ("after assignment",var)
    
fun()

after assignment 22


## Nested List

In [177]:
l=[1,2,3,[4,5],["one","two","three"]]
print(l)

print (l[-1])
print(l[-1][-2])
print(l[-2][0])

[1, 2, 3, [4, 5], ['one', 'two', 'three']]
['one', 'two', 'three']
two
4


In [187]:

l=[1,2,3,[4,5],["one","two","three"]]
l.append(["four","five","six"])
l.extend([[6,7,8],9,[10,11,12]])
l

[1,
 2,
 3,
 [4, 5],
 ['one', 'two', 'three'],
 ['four', 'five', 'six'],
 [6, 7, 8],
 9,
 [10, 11, 12]]

# list Functions

In [217]:
l.append("name")
print (l)
ls=[1,2,3,4,7,10,112,3]
print(ls.reverse())
print (ls)
ls.remove(112)
print(ls)

['name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', 'name', [10, 11, 12], 9, [6, 7, 8], ['four', 'five', 'six'], ['one', 'two', 'three'], [4, 5], 3, 2, 1, 'name', 'name', 'name', 'name', 'name', 'name']
None
[3, 112, 10, 7, 4, 3, 2, 1]
[3, 10, 7, 4, 3, 2, 1]


# list Comprehension

#### create an list from exsiting list

### syntax will be output + list 

In [206]:
part=[x**2 for x in range (0,11)]
print(part)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [210]:
even =[x for x in range(0,11) if x%2==0]
print(even)

[0, 2, 4, 6, 8, 10]


In [212]:
findit=["true" if x%2==0 else "False" for x in range(0,11) ]
print(findit)

['true', 'False', 'true', 'False', 'true', 'False', 'true', 'False', 'true', 'False', 'true']


In [214]:
add =[x+y for x in ["data"] for y in ["Analyist","Scientist"]]
print (add)

['dataAnalyist', 'dataScientist']


## Enumerate 

In [247]:
x1 =["state","city","place"]
x2=list(enumerate(x1,112))
print(x2)

for val in x2:
    print (val)
    
for key,pair in x2:
    print (key,"-------",pair)
    
    
print(x2[2])

x3=list([enumerate(x) for x in x1])
x3=list([x for x in enumerate(x1)])



[(112, 'state'), (113, 'city'), (114, 'place')]
(112, 'state')
(113, 'city')
(114, 'place')
112 ------- state
113 ------- city
114 ------- place
(114, 'place')


## Changing the tuple

### if tuple has a mutable datattpe in it .we can make tuple mutable

In [237]:
tup=(1,2,3,[7,9,10])
type(tup)

tuple

In [239]:
tup[3][1]="Hi There"
tup

(1, 2, 3, [7, 'Hi There', 10])

In [240]:
tup[3]="hi there"
print(tup)

TypeError: 'tuple' object does not support item assignment

# 1.	Difference between variable and constant? Create and import a constant, then print the values of constant


In [252]:
import constants

print(constants.Pi,"---",constants.gravity)

3.14 --- 9.8


# 2.	Convert a float to integer, then convert it to string. Convert a list into a set. Convert a string into a list

In [256]:
float = 3.14

print ("string-->",str(int(float)))
print(type(str(int(float))))

print(set(list(range(1,10))))

print(list("Hello ,Good Morning"))

string--> 3
<class 'str'>
{1, 2, 3, 4, 5, 6, 7, 8, 9}
['H', 'e', 'l', 'l', 'o', ' ', ',', 'G', 'o', 'o', 'd', ' ', 'M', 'o', 'r', 'n', 'i', 'n', 'g']


# 3.	Add an integer/float with a string using type casting

In [257]:
s = "56"
b = 57
print("add ",b+int(s))


add  113


# 4.	Write a simple for loop to iterate through a string and break the iteration before the last iteration


In [259]:
str = "Hello there"
for i in range(len(str)):
    if (i==(len(str)-1)):
        break
    else:
        print (str[i])
    

H
e
l
l
o
 
t
h
e
r


 # 5.	Write a function to return the reminder of 2 numbers given through function arguments

In [260]:
def reminder(a,b):
    return (a%b)

print(reminder(4,5))

4


# 6.	Add a docstring to above function and print the same

In [262]:
def docstr():
    """This is a dummy function for testing"""
print(docstr.__doc__)

This is a dummy function for testing


# 7.	Write a function with one and 2 default arguments and print the same.

In [267]:
def trail(a="Hello",b="Everyone"):
    return a+" "+b

print(trail())

def trail1(b,a="Hello"):
    return a+" "+b

print(trail())
print(trail1("Good Afternoon"))



Hello Everyone
Hello Everyone
Hello Good Afternoon


# 8.	Can a non-default arg follow a default argument? Can two default args be mixed while calling a function? If we mix a default argument and positional argument, what is the constraint?

 # No . default argumenet should be at the last, or all the argument should have the default value

# 9.	Write a lambda function to add first to number, then divide the sum by third number

In [194]:
cab =lambda x,y,z:(x+y)/z
print(cab(12,9,3))


j=lambda x,y: x if x>y y if y>x 

j(5,6)
print(j)

SyntaxError: invalid syntax (<ipython-input-194-f4798fc8c610>, line 5)

# 10.	Create a list of first 20 numbers using a range function, then use a filter function to output the odd numbers

In [277]:
ls=range(1,21)
cd = list(filter(lambda x:x%2!=0,ls))
print(cd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


# 11.	Create a list of 5 numbers and use a lambda function to square each number in a list

In [193]:
lk = range(0,5)

ls =list(map(lambda x:x*2,lk))
print(ls)
ls =list(filter(lambda x:x*2,lk))
print(ls)

[0, 2, 4, 6, 8]
[1, 2, 3, 4]


# 12.	Use the ‘global’ keyword to modify a global variable of value ‘5’, then square it and print the output

In [286]:
var = 10
def my_fn():
    global var
    var=5
    return (var*var)

print (my_fn())

25


# Perform list concatenation of 2 lists, then add one element in the beginning of the concatenated list and add 2 elements before the last element of the list

In [293]:
ls = [1,2,3,4]
ls2=[5,6,7]
ls=ls+ls2
print(ls)
ls[0]="first"
print(ls)
ls[(len(ls)-2)]="before last"
print (ls)


[1, 2, 3, 4, 5, 6, 7]
['first', 2, 3, 4, 5, 6, 7]
['first', 2, 3, 4, 5, 'before last', 7]


# 14.	Create a list 0 to 10 and remove all even numbers using ‘remove’ method (Use ‘for’ and ‘if)

In [295]:
ls = list(range(0,11))
for i in ls:
    if i%2==0:
        ls.remove(i)
print(ls)

[1, 3, 5, 7, 9]


# 15.	Remove first 5 elements in a list of numbers 10 to 20 using list comprehension

In [300]:
ls=range(10,21)
lf=[x for x in ls[5:]]
print(lf)


[15, 16, 17, 18, 19, 20]


# 16.	If x = [‘Python ’, ‘R ’] and y = [‘Language’, ‘Programming], using list comprehension print the following: ['Python Language', 'Python Programming', 'R Language', 'R Programming']

In [302]:
check =[x+" "+y for x in ['python','R'] for y in ["Language","Programming"]]
print(check)

['python Language', 'python Programming', 'R Language', 'R Programming']


# 17.	Create a tuple (of 3 elements) without parenthesis and unpack each element. Also create a tuple with just one value in it

In [310]:
tup= tuple("",)
type(tup)

tup=(1,2,3)
tup[0]

1

# 18.	Is there a way to change the elements of a tuple? Code an example

In [311]:
tup = (1,2,3,[4,5,6])
tup[3][2]="Changed"
print(tup)

(1, 2, 3, [4, 5, 'Changed'])


# 19.	Using escape sequence, print the following: What’s up, guys! How’s it going?

In [320]:
print ('What\'s up, guys! How’s it going?')

What's up, guys! How’s it going?


# 20.	Can we use insert method in a set to modify? Explain why? 

In [1]:
set1 = set{}
# Set is unordered . can't insert using index . but we can update


SyntaxError: invalid syntax (<ipython-input-1-500715a6b00d>, line 1)

# Iterators 

In [6]:
mylist=[1,2,5,6,7,8]
print(iter.__doc__)
it = iter(mylist)
print(next(it))
for i in mylist:
    print("------>",i)
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))



iter(iterable) -> iterator
iter(callable, sentinel) -> iterator

Get an iterator from an object.  In the first form, the argument must
supply its own iterator, or be a sequence.
In the second form, the callable is called until it returns the sentinel.
1
------> 1
------> 2
------> 5
------> 6
------> 7
------> 8
2
5
6
7
8


StopIteration: 

# Generators

## yield statement is used in Generators . same as iter .. will use Next statement .. 

In [9]:
def mygen():
    n=1
    print("printing first")
    yield n
    n=n+1
    print("printing Second")
    yield n
    n=n+1
    print("printing third")
    yield n

mygen()

<generator object mygen at 0x000001CFF2DD10C0>

In [12]:
a=mygen()
print(next(a))

printing first
1


In [13]:
print(next(a))

printing Second
2


## Printing the string in reverse order using Generator

In [16]:
def reverseastring(data):
    str_len=len(data)
    for i in range((str_len-1),-1,-1):
        yield data[i]
        
ab=reverseastring("data")
print(next(ab))
print(next(ab))
print(next(ab))
print(next(ab))

a
t
a
d


# List comprehension VS Generator Expression 

## List comprehension is surrounded with []
## Generator Expression is surrounded with () 


In [18]:
lsc=[x*2 for x in range(0,5)]
print(lsc)

[0, 2, 4, 6, 8]


In [22]:
ge=(x*2 for x in range(0,5))
print(next(ge))
print(next(ge))
print(next(ge))
print(next(ge))
print(next(ge))


0
2
4
6
8


# operators  in GE and List Comphresion 




In [23]:
sum(x*2 for x in range(0,5))

20

#python Closures

#Nested Function 

Return method is not required for returning the function

In [32]:
def function(var):
    def fun1():
        var1 = var+2
        return var1
    fun1()
    

In [39]:
print(function(5))

None


In [65]:
def function(var):
    def fun1():
        global var
        var = var+2
        print(var)
        return var
  
    return fun1()

In [82]:
a=function(6)
print(a)

52
52


# Decorators 

In [49]:
def square(x):
    return(x*x)
def cube(x):
    return(x**3)
def calc(fn,x):
    result=fn(x)
    return result


In [50]:
calc(square,5)

25

In [67]:
calc(cube,4)

64

In [81]:
def decor(fn):
    def nested_fn():
        fn()
        print("THis is the loop for the nested")
    return nested_fn()

def ordinary_f():
    print("Implementing Od Function")

dc=decor(ordinary_f)
#ordinary_fn=decor(ordinary_fn)

Implementing Od Function
THis is the loop for the nested


In [186]:
def dc_fn1(func):
    def nested_fn(x,y):
       
        if y==0:
            return("Can't divide the number by Zero")
            
        else:
            print ("Dividing the ",x, " by ",y)
            return func(x,y)
    return nested_fn

@dc_fn1
def dde(x,y):
    return (x/y)


        




In [188]:
dde(5,5)

Dividing the  5  by  5


1.0

In [106]:
import numpy as np

In [107]:
a1=np.array([1,2,4,5,6])

In [110]:
print(a1.base)

None


In [111]:
a1.ndim

1

In [112]:
a1.shape

(5,)

In [113]:
a2=np.array([[1,2,3],[5,6,7]],dtype=float)

In [114]:
a2

array([[1., 2., 3.],
       [5., 6., 7.]])

In [116]:
a2.shape

(2, 3)

In [119]:
a2.reshape(1,6)


array([[1., 2., 3., 5., 6., 7.]])

In [120]:
a2.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [5.],
       [6.],
       [7.]])

In [122]:
a2.reshape(3,2)

array([[1., 2.],
       [3., 5.],
       [6., 7.]])

In [126]:
a3=np.zeros(6)

In [127]:
a3

array([0., 0., 0., 0., 0., 0.])

In [128]:
a3.reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [140]:
x1=[[1,2],[4,5],[1,4]]
a1=np.array(x1)
a1

array([[1, 2],
       [4, 5],
       [1, 4]])

In [131]:
a4=np.arange(0,10,2)

In [132]:
a4

array([0, 2, 4, 6, 8])

In [135]:
a5=np.linspace(0,10,9)

In [136]:
a5

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [141]:
a6=np.arange(10)

In [142]:
a6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
a7=a6[1:5:2]

In [148]:
a7

array([1])

In [151]:
a8=np.array([[1,2],[3,4],[5,6]])

In [152]:
a8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [156]:
a9=a8[a8>2]

In [157]:
a9

array([3, 4, 5, 6])

In [174]:
a10 = np.array([1,5,np.nan,6,np.nan,0])
a10


array([ 1.,  5., nan,  6., nan,  0.])

In [177]:
a10=a10[~np.isnan(a10)]
a10

array([1., 5., 6., 0.])

In [195]:
a11=np.array([[1,2],[3,4]])

In [196]:
a11

array([[1, 2],
       [3, 4]])

In [201]:
a12=a11*a11
a12

array([[ 1,  4],
       [ 9, 16]])

In [202]:
a12.T

array([[ 1,  9],
       [ 4, 16]])

In [203]:
a12.flatten()

array([ 1,  4,  9, 16])

In [ ]:
# Axis  1 and axis 0 
#Stack COncontenate

In [208]:
np.concatenate((a11,a12),axis=1)

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16]])

In [217]:
t=np.concatenate((a11,a12))
print(t)
t.ndim

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


2

In [214]:
c=np.stack([a11,a12])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 1,  4],
        [ 9, 16]]])

In [223]:
c.ndim
print(c.shape)

(2, 4)


In [222]:
c=np.hstack([a11,a12])
print(c)
print(c.shape)
c.ndim

[[ 1  2  1  4]
 [ 3  4  9 16]]
(2, 4)


2

# Append

In [224]:
np.append(c,[4,5,6,7])

array([ 1,  2,  1,  4,  3,  4,  9, 16,  4,  5,  6,  7])

In [225]:
a11

array([[1, 2],
       [3, 4]])

In [241]:
a18=np.insert(a11,1,list(range(0,2)),axis=1)
a18


array([[1, 0, 2],
       [3, 1, 4]])

In [237]:
print(a11)
a18=np.insert(a11,[0,2],[10,18],axis=1)
a18


[[1 2]
 [3 4]]


array([[10,  1,  2, 18],
       [10,  3,  4, 18]])

In [233]:
a19=np.insert(a11,1,[9,8],axis=1)
a19


array([[1, 9, 2],
       [3, 8, 4]])

In [250]:
np.percentile(a19,100,axis=1)

array([9., 8.])

In [251]:
np.percentile(a19,100,axis=0)

array([3., 9., 4.])

In [252]:
np.mean(a11)

2.5

# Pandas

In [256]:
import pandas as pa

p=pa.Series(range(10,60,2))

In [257]:
p

0     10
1     12
2     14
3     16
4     18
5     20
6     22
7     24
8     26
9     28
10    30
11    32
12    34
13    36
14    38
15    40
16    42
17    44
18    46
19    48
20    50
21    52
22    54
23    56
24    58
dtype: int64

In [258]:
import pandas as pa

p=pa.Series(range(10,60,2),index=range(25,50))

In [259]:
p

25    10
26    12
27    14
28    16
29    18
30    20
31    22
32    24
33    26
34    28
35    30
36    32
37    34
38    36
39    38
40    40
41    42
42    44
43    46
44    48
45    50
46    52
47    54
48    56
49    58
dtype: int64

In [261]:
dic={"a":"one","b":"two","c":"three"}
dic

{'a': 'one', 'b': 'two', 'c': 'three'}

In [262]:
d=pa.Series(dic)

In [263]:
d

a      one
b      two
c    three
dtype: object

In [264]:
d["b"]

'two'

In [267]:
type(d)

pandas.core.series.Series

In [268]:
dic={"a":"one","b":"two","c":"three"}
e=pa.Series(dic,index=["a","b","c","d"])

In [269]:
e

a      one
b      two
c    three
d      NaN
dtype: object

In [270]:
e[:2]

a    one
b    two
dtype: object

In [271]:
e["c"]

'three'

In [272]:
df=pa.DataFrame()

In [274]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [282]:
de=pa.DataFrame(list(range(0,10)))

In [283]:
de

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [284]:
 type(df)

pandas.core.frame.DataFrame

In [292]:
dic={"col1":"value1","col2":"value2","col3":"value3"}

SyntaxError: invalid syntax (<ipython-input-292-1668f267d428>, line 1)

In [286]:
dic

{'col1': 'value1', 'col2': 'value2', 'col3': 'value3'}

In [290]:
df=pa.DataFrame(dic,index=[1])

In [291]:
df

col1    col2    col3
1  value1  value2  value3

In [299]:
dic={"Age":[23,26,29],"Mark":[90,99,80]}

In [300]:
e=pa.DataFrame(dic,index=[1,2,3])

In [302]:
e

Age  Mark
1   23    90
2   26    99
3   29    80

In [304]:
e.drop("Age",axis=1)

Mark
1    90
2    99
3    80

In [307]:
e.drop(2,axis=0)

Age  Mark
1   23    90
3   29    80

In [308]:
e

Age  Mark
1   23    90
2   26    99
3   29    80

In [309]:
e.drop("Age",axis=1,inplace=True)

In [310]:
e

Mark
1    90
2    99
3    80